import nextEslintPluginNext from '@next/eslint-plugin-next';
import nx from '@nx/eslint-plugin';
import baseConfig from '../../eslint.config.mjs';

export default [
  { plugins: { '@next/next': nextEslintPluginNext } },
  ...nx.configs['flat/react-typescript'],
  ...baseConfig,
  {
    // next-env.d.ts is auto-generated by Next.js ("This file should not be
    // edited") and is regenerated with double-quoted imports, which
    // conflicts with this project's `quotes: single` rule.
    ignores: ['.next/**/*', '**/out-tsc', 'next-env.d.ts'],
  },
  {
    // Flat-config equivalent of the old `plugin:@nrwl/nx/*` extends: those
    // presets are already applied above via `...baseConfig` / `nx.configs`.
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          // Mirrors the root config's allowance for relative eslint.config.js
          // imports: tailwind.config.js also needs a relative require of a
          // shared lib's tailwind config since it's a build-tool config file,
          // not app source subject to npm-scoped project boundaries.
          allow: ['^.*/tailwind\\.config\\.[cm]?js$'],
          depConstraints: [
            {
              sourceTag: '*',
              onlyDependOnLibsWithTags: ['*'],
            },
          ],
        },
      ],
    },
  },
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    rules: {
      'max-len': ['error', { code: 140 }],
      'no-extra-boolean-cast': 'off',
      quotes: ['error', 'single', { avoidEscape: true }],
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '_' }],
      '@typescript-eslint/no-inferrable-types': 'off',
    },
  },
];
